# -*- coding: utf-8 -*-
"""Video Games

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UQE4RTmc8-idxagLSEEE-FBe4e_Wr5zX

#Importando DataFrame
"""

# -Histogramas de quantos jogos cada gênero possui nos primeiros 150 títulos do rank  
# -Um gráfico de dispersão entre o ano da publicação e o total de vendas da Nintendo nos últimos 10 anos
# -As 5 maiores “publishers” em vendas nos Estados Unidos

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

video_games = pd.read_csv('dataset_video_games.csv')
video_games.head(5)

video_games.shape

video_games.describe()

"""#Histogramas de quantos jogos cada gênero possui nos primeiros 150 títulos do rank"""

video_games_150 = video_games.head(150)
video_games_150.Genre.value_counts()

total_por_genero = video_games_150.Genre.value_counts().to_frame().reset_index()
total_por_genero.columns =['Genero','total']
total_por_genero

sns.catplot(x='Genre', kind='count', data = video_games_150,
            aspect = 2,
            palette = 'GnBu_d',
            order = video_games_150.Genre.value_counts().index)

"""#Um gráfico de dispersão entre o ano da publicação e o total de vendas da Nintendo nos últimos 10 anos"""

pub_ano = video_games.query('Publisher == "Nintendo"' and 'Year >= 2010')
df1 =pub_ano.groupby('Year').sum().reset_index()
df1

year = df1.Year
global_sales = df1.Global_Sales
data_frame =pd.DataFrame(data = {'Year':year,'Sales':global_sales})
data_frame

data_frame.plot.scatter(x = 'Year', y = 'Sales',s=20)

"""#As 5 maiores “publishers” em vendas nos Estados Unidos"""

pub_agrupado = video_games.groupby('Publisher').sum()
pub_agrupado_ordenado= pub_agrupado.sort_values(['NA_Sales'],ascending=False) 
maiores_pub = pub_agrupado_ordenado['NA_Sales'].head(5).to_frame().reset_index()
maiores_pub.columns = ['Publisher','Vendas USA']
maiores_pub

